version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://admin:admin@db:5432/paiement
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: paiement
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  worker:
    build: .
    command: rq worker --url redis://redis:6379/0 paiement-tasks
    depends_on:
      - redis
      - db
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/paiement
      - REDIS_URL=redis://redis:6379/0

volumes:
  postgres_data:
